In [4]:

import numpy as np
import math
from scipy.spatial.transform import Rotation as R

In [5]:
a=R.from_euler('xyz', [0.35,  1.002,  0.35], degrees=False)

In [6]:
a.as_matrix()

array([[ 0.50596332, -0.05071607,  0.86106272],
       [ 0.18469103,  0.98148719, -0.05071607],
       [-0.84254991,  0.18469103,  0.50596332]])

In [7]:
b=R.from_euler('xyz', [0.0,  0.1,  0.0], degrees=False)

In [17]:
a=R.from_euler('xyz', [0.35,  1.002,  0.35], degrees=False)
b=R.from_euler('xyz', [0.0,  -0.1,  0.0], degrees=False)
c=np.matmul(a.as_matrix(),b.as_matrix())
d=R.from_matrix(c)
d.as_euler('xyz',degrees=False)

array([0.30456104, 0.90727543, 0.29438932])

In [12]:
d.as_euler('xyz',degrees=False)

array([0.41488603, 1.09483512, 0.42478199])

In [9]:
c=np.matmul(a.as_matrix(),b.as_matrix())

array([[ 0.41747278, -0.05071607,  0.90727304],
       [ 0.1888315 ,  0.98148719, -0.03202436],
       [-0.88885271,  0.18469103,  0.41932097]])